### ISSUE TITLE
Check if ksh existing

### ISSUE THREAD

**Issue by ghost** [sergiotocalini/mysbix#1]
Hello,

please add a check and install of ksh or add a discreption to the readme.
```
#Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64 GNU/Linux
./deploy_zabbix.sh
/usr/bin/env: ‘ksh’: No such file or directory
```

**Comment by sergiotocalini** [comment]
I've just added the dependencies and how should you use the deploy_zabbix script.
